version: '3.8'
services:
  # Kita hanya butuh Database di Docker
  db:
    image: mysql:8.0
    ports:
      - "3306:3306" # Agar bisa diakses dari laptop (HeidiSQL/DBeaver)
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: simak_event_attendance
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: